sudo: false
language: node_js
node_js:
  - "10"
install:
  - npm install
script: "npm run $TEST_SUITE"
after_success:
  - "npm run coverage"
env:
  - TEST_SUITE=validate
  - TEST_SUITE=test
cache:
  directories:
    - node_modules
    - packages/walt-loader/node_modules
    - packages/webpack-walt-examples/node_modules
    - packages/walt-compiler/node_modules
    - packages/walt-docs/node_modules
    - packages/walt-link/node_modules

